FluentValidation_JwtToken/Models/ErrorViewModel.cs
namespace FluentValidation_JwtToken.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FluentValidation_JwtToken/Models/Filme.cs
using System.ComponentModel.DataAnnotations;

namespace FluentValidation_JwtToken.Models
{
    public class Filme
    {
        [Key]
        public int Id { get; set; }
        public string? Titulo { get; set; }
        public string? Diretor { get; set; }
        public int Ano { get; set; }
    }
}

FluentValidation_JwtToken/Controllers/FilmeController.cs
using FluentValidation_JwtToken.Models;
using FluentValidation_JwtToken.Service;
using FluentValidation_JwtToken.Validator;
using Microsoft.AspNetCore.Mvc;

namespace FluentValidation_JwtToken.Controllers
{
    public class FilmeController : Controller
    {
        private readonly IFilme _filme;


        public FilmeController(IFilme filme)
        {
            _filme = filme;
        }
        public async Task<IActionResult> Index()
        {
            var filme = await _filme.ObterTodosFilmes();
            return View(filme);
        }
        [HttpPost]
        public async Task<IActionResult> New(Filme filme)
        {
            var validator = new FilmeValidator();
            var result = validator.Validate(filme);

            if (result.IsValid)
            {
                await _filme.AdicionarFilme(filme);
                TempData["sucess"] = "Filme Criado Com Sucesso!!";
                return RedirectToAction("New");
            }


            foreach (var failure in result.Errors)
            {
                ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
            }


            return View(filme);
        }


        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
    
        [HttpGet]
        public IActionResult Delete(int? id)
        {

            _filme.Remove(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)

        {
            var buscar = await _filme.BuscaFilmePorId(id);

            return View(buscar);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Filme filme)
        {
            if (ModelState.IsValid)
            {
              await _filme.AtualizarFilme(filme);
                TempData["MensagemSucesso"] = "Filme alterado com sucesso!";
                return RedirectToAction("Index");
            }
            return View(filme);

        }
    }
}

FluentValidation_JwtToken/Controllers/HomeController.cs
using FluentValidation_JwtToken.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FluentValidation_JwtToken.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FluentValidation_JwtToken/Views/Filme/Index.cshtml
@model List<Filme>


<a class="btn btn-primary" asp-controller="Filme" asp-action="New">Adicionar novo Filme</a>

    
@if(Model.Count == 0){
    <p class="text-center">Nenhum Filme Encontrado</p>
}else{
    <div class="table-responsive">
        <table class="table table-striped" id="Table-Employee">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Titulo</th>
                    <th scope="col">Diretor</th>
                    <th scope="col">Ano</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var f in Model)
                {
                    <tr>
                        <td>@f.Titulo</td>
                        <td>@f.Diretor</td>
                        <td>@f.Ano</td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@f.Id" class="btn btn-danger">Delete</a>
                        </td>
                        <td>
                            <a class="btn btn-secondary btn-md" asp-action="Update" asp-route-id="@f.Id">Editar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>


}

FluentValidation_JwtToken/Views/Filme/New.cshtml
@model FluentValidation_JwtToken.Models.Filme


<div class="text-center"> <h1>Adicionar Filme</h1></div>

@if (TempData["sucess"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert">X</button>
        @TempData["sucess"]
    </div>
}
<div class="col-md-6 mx-auto">
<form asp-action="New" method="post">
    <div class="form-group mx-auto">
            <label asp-for="Titulo" class="control-label">Título do Filme</label>
            <input asp-for="Titulo" class="form-control" />
            <span asp-validation-for="Titulo" class="text-danger"></span>
    </div>
       
    <div class="form-group">
            <label asp-for="Diretor" class="control-label">Diretor do Filme</label>
            <input asp-for="Diretor" class="form-control" />
            <span asp-validation-for="Diretor" class="text-danger"></span>
    </div>
        <div class="form-group">
            <label asp-for="Ano" class="control-label">Ano de Lançamento</label>
            <input asp-for="Ano" class="form-control" />
            <span asp-validation-for="Ano" class="text-danger"></span>
        </div>


        <button type="submit" class="btn btn-primary mt-2">Adicionar</button>
</form>
</div>

FluentValidation_JwtToken/Views/Filme/Update.cshtml
@model Filme

<h2 class="text-center">Alterar Filme</h2>

<div class="row">
    <div class="col-md-6 mx-auto">
        <form asp-controller="Filme" asp-action="Update" method="POST">
            <input type="hidden" asp-for="Id"/>

            <div class="form-group">
                <label asp-for="Titulo"></label>
                <input type="text" asp-for="Titulo" class="form-control"/>
            </div>

            <div class="form-group">
                <label asp-for="Diretor"></label>
                <input type="text" asp-for="Diretor" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Ano"></label>
                <input type="number" asp-for="Ano" class="form-control"/>
            </div>

            <input type="submit" class="btn btn-primary btn-block" value="Save"/>

        </form>
    </div>
</div>

FluentValidation_JwtToken/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container d-flex justify-content-center align-items-center">
    <div class="text-center">
        <h1 class="display-4">Olá, Que seu dia Seja Abençoado :)</h1>
    </div>
</div>

FluentValidation_JwtToken/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FluentValidation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FluentValidation_JwtToken.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FluentValidation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filme" asp-action="Index">Lista De Filmes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FluentValidation <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>